const l = require("../dependence/lodash.js");
const math = require("../dependence/math.js");
const moment = require("../dependence/moment");
const j = require('../dependence/judge.min');
const c = console.log;
const {
  getOwnPropertyNames,
  getPrototypeOf,
} = Object;
const {
  max,
  trunc,
  random,
  floor,
  sqrt,
} = Math;
const type = Function.prototype.call.bind(Object.prototype.toString);

c(getOwnPropertyNames(j))
const propertyNameArr = ['version',
  'type',
  'isWindow',
  'isDocument',
  'isArray',
  'isObject',
  'isObjectLike',
  'isEmptyObject',
  'isPlainObject',
  'include',
  'isArrayLike',
  'isArrayLikeObject',
  'kernel',
  'platform',
  'isElectron',
  'iosDevice',
  'iosVersion',
  'androidVersion',
  'isMobile',
  'isPc',
  'isExist',
  'isNull',
  'isUndefined',
  'isNumber',
  'isNumberic',
  'isPositiveInteger',
  'isInteger',
  'isUptoAdecimal',
  'lt',
  'inArray',
  'isTouchDevice',
  'email',
  'hasLowerCase',
  'hasNumber',
  'hasCapital',
  'isBrowser',
  'isFunction',
  'isEqual',
  'isLength',
  'size',
  'isHttps',
  'isUnique',
  'isString',
  'isInt',
  'isJson',
  'hasClass',
  'isError',
  'isChar',
  'isArguments',
  'isEmpty',
  'qqNumber',
  'phoneNumber',
  'isLetter',
  'isAlpha',
  'includeChinese',
  'onlyChinese',
  'onlyNumber',
  'isElement',
  'isSet',
  'isRegExp',
  'idNumber',
  'isEven',
  'isOdd',
  'min',
  'hasHash',
  'getHash',
  'has',
  'zipCode',
  'isChromium',
  'isOnline',
  'hasSpecialChar',
  'position',
  'isNativeFn',
  'strLength',
  'isLeapYear',
  'isDate',
  'isUrl'];
c(j.type(j));

c(j.isObject([]))
c(j.phoneNumber('1832992191'))
